#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Render.Resource", IsApplication=true)]

namespace Render
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int BotonLogin = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int SeparadorListaAvisosPendientes = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int render_background = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int theme_devicedefault_background = 2131034115;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hojatrabajo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_render = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int imprimirhojatrabajo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int pendientes = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int recogidos = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int sincronizacion = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sincronizar = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splash_screen = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080054
			public const int BotonAvisosPendientes = 2131230804;
			
			// aapt resource value: 0x7f080055
			public const int BotonAvisosRecogidos = 2131230805;
			
			// aapt resource value: 0x7f080056
			public const int BotonAvisosSinSincronizar = 2131230806;
			
			// aapt resource value: 0x7f080058
			public const int BotonFinalizarHojadeTrabajo = 2131230808;
			
			// aapt resource value: 0x7f080059
			public const int BotonImprimirHojadeTrabajo = 2131230809;
			
			// aapt resource value: 0x7f08005a
			public const int BotonSincronizar = 2131230810;
			
			// aapt resource value: 0x7f080052
			public const int Recodar_DatosAcceso = 2131230802;
			
			// aapt resource value: 0x7f080065
			public const int Spinner = 2131230821;
			
			// aapt resource value: 0x7f08005c
			public const int action_acumular = 2131230812;
			
			// aapt resource value: 0x7f080060
			public const int action_anular = 2131230816;
			
			// aapt resource value: 0x7f080061
			public const int action_cancelar = 2131230817;
			
			// aapt resource value: 0x7f080063
			public const int action_cancelar_recogido = 2131230819;
			
			// aapt resource value: 0x7f08005d
			public const int action_cerareimprimir = 2131230813;
			
			// aapt resource value: 0x7f08005e
			public const int action_cerrar = 2131230814;
			
			// aapt resource value: 0x7f080062
			public const int action_cerrarSesion = 2131230818;
			
			// aapt resource value: 0x7f08005f
			public const int action_editar = 2131230815;
			
			// aapt resource value: 0x7f080064
			public const int action_imprimir_recogido = 2131230820;
			
			// aapt resource value: 0x7f08005b
			public const int action_rechazar = 2131230811;
			
			// aapt resource value: 0x7f080018
			public const int btn_FAPesar = 2131230744;
			
			// aapt resource value: 0x7f080051
			public const int button1 = 2131230801;
			
			// aapt resource value: 0x7f08004e
			public const int editText1 = 2131230798;
			
			// aapt resource value: 0x7f080050
			public const int editText2 = 2131230800;
			
			// aapt resource value: 0x7f080039
			public const int etSearch = 2131230777;
			
			// aapt resource value: 0x7f08004d
			public const int imageView1 = 2131230797;
			
			// aapt resource value: 0x7f080038
			public const int listView = 2131230776;
			
			// aapt resource value: 0x7f08002e
			public const int llContainer = 2131230766;
			
			// aapt resource value: 0x7f080053
			public const int myButton = 2131230803;
			
			// aapt resource value: 0x7f080001
			public const int textView1 = 2131230721;
			
			// aapt resource value: 0x7f08004f
			public const int textView2 = 2131230799;
			
			// aapt resource value: 0x7f080000
			public const int toggleButton1 = 2131230720;
			
			// aapt resource value: 0x7f08003c
			public const int txtAG = 2131230780;
			
			// aapt resource value: 0x7f080031
			public const int txtAGCabecera = 2131230769;
			
			// aapt resource value: 0x7f08003a
			public const int txtAviso = 2131230778;
			
			// aapt resource value: 0x7f08002f
			public const int txtAvisoCabecera = 2131230767;
			
			// aapt resource value: 0x7f080043
			public const int txtAvisoR = 2131230787;
			
			// aapt resource value: 0x7f080057
			public const int txtAvisosSinSincronizar = 2131230807;
			
			// aapt resource value: 0x7f08004b
			public const int txtCodMotivo = 2131230795;
			
			// aapt resource value: 0x7f08004c
			public const int txtDescripcionMotivo = 2131230796;
			
			// aapt resource value: 0x7f08003b
			public const int txtEspecie = 2131230779;
			
			// aapt resource value: 0x7f080030
			public const int txtEspecieCabecera = 2131230768;
			
			// aapt resource value: 0x7f080044
			public const int txtEspecieR = 2131230788;
			
			// aapt resource value: 0x7f080035
			public const int txtExplotacionCabecera = 2131230773;
			
			// aapt resource value: 0x7f080040
			public const int txtExplotación = 2131230784;
			
			// aapt resource value: 0x7f080046
			public const int txtExplotaciónR = 2131230790;
			
			// aapt resource value: 0x7f08003d
			public const int txtFAviso = 2131230781;
			
			// aapt resource value: 0x7f080032
			public const int txtFAvisoCabecera = 2131230770;
			
			// aapt resource value: 0x7f080045
			public const int txtFAvisoR = 2131230789;
			
			// aapt resource value: 0x7f080048
			public const int txtKiloR = 2131230792;
			
			// aapt resource value: 0x7f080049
			public const int txtMotivoAnulacionR = 2131230793;
			
			// aapt resource value: 0x7f08003f
			public const int txtNombre = 2131230783;
			
			// aapt resource value: 0x7f080034
			public const int txtNombreCabecera = 2131230772;
			
			// aapt resource value: 0x7f080047
			public const int txtNombreR = 2131230791;
			
			// aapt resource value: 0x7f080033
			public const int txtPoblacionCabecera = 2131230771;
			
			// aapt resource value: 0x7f08003e
			public const int txtPoblación = 2131230782;
			
			// aapt resource value: 0x7f08004a
			public const int txtPoblaciónR = 2131230794;
			
			// aapt resource value: 0x7f080041
			public const int txtTfno1 = 2131230785;
			
			// aapt resource value: 0x7f080036
			public const int txtTfno1Cabecera = 2131230774;
			
			// aapt resource value: 0x7f080042
			public const int txtTfno2 = 2131230786;
			
			// aapt resource value: 0x7f080037
			public const int txtTfno2Cabecera = 2131230775;
			
			// aapt resource value: 0x7f080003
			public const int txt_FAAviso = 2131230723;
			
			// aapt resource value: 0x7f08001a
			public const int txt_FAAvisoRecogido = 2131230746;
			
			// aapt resource value: 0x7f080008
			public const int txt_FACodExplotacion = 2131230728;
			
			// aapt resource value: 0x7f08001f
			public const int txt_FACodExplotacionRecogido = 2131230751;
			
			// aapt resource value: 0x7f080011
			public const int txt_FACrotal = 2131230737;
			
			// aapt resource value: 0x7f080028
			public const int txt_FACrotalRecogido = 2131230760;
			
			// aapt resource value: 0x7f08000a
			public const int txt_FADireccion = 2131230730;
			
			// aapt resource value: 0x7f080021
			public const int txt_FADireccionRecogido = 2131230753;
			
			// aapt resource value: 0x7f08000e
			public const int txt_FAEspecie = 2131230734;
			
			// aapt resource value: 0x7f080025
			public const int txt_FAEspecieRecogido = 2131230757;
			
			// aapt resource value: 0x7f08000d
			public const int txt_FAEstadoSiniestro = 2131230733;
			
			// aapt resource value: 0x7f080024
			public const int txt_FAEstadoSiniestroRecogido = 2131230756;
			
			// aapt resource value: 0x7f080006
			public const int txt_FAExplotacion = 2131230726;
			
			// aapt resource value: 0x7f08001d
			public const int txt_FAExplotacionRecogido = 2131230749;
			
			// aapt resource value: 0x7f080005
			public const int txt_FAFechaFinPoliza = 2131230725;
			
			// aapt resource value: 0x7f08001c
			public const int txt_FAFechaFinPolizaRecogido = 2131230748;
			
			// aapt resource value: 0x7f080010
			public const int txt_FAFechaMuerte = 2131230736;
			
			// aapt resource value: 0x7f080027
			public const int txt_FAFechaMuerteRecogido = 2131230759;
			
			// aapt resource value: 0x7f08000f
			public const int txt_FAFechaNacimiento = 2131230735;
			
			// aapt resource value: 0x7f080026
			public const int txt_FAFechaNacimientoRecogido = 2131230758;
			
			// aapt resource value: 0x7f080004
			public const int txt_FAFechaRecogida = 2131230724;
			
			// aapt resource value: 0x7f08001b
			public const int txt_FAFechaRecogidaRecogido = 2131230747;
			
			// aapt resource value: 0x7f080007
			public const int txt_FANombre = 2131230727;
			
			// aapt resource value: 0x7f08001e
			public const int txt_FANombreRecogido = 2131230750;
			
			// aapt resource value: 0x7f080012
			public const int txt_FANumAnimales = 2131230738;
			
			// aapt resource value: 0x7f080029
			public const int txt_FANumAnimalesRecogido = 2131230761;
			
			// aapt resource value: 0x7f080002
			public const int txt_FANumeroAviso = 2131230722;
			
			// aapt resource value: 0x7f080019
			public const int txt_FANumeroAvisoRecogido = 2131230745;
			
			// aapt resource value: 0x7f080017
			public const int txt_FAObservaciones = 2131230743;
			
			// aapt resource value: 0x7f08002d
			public const int txt_FAObservacionesRecogido = 2131230765;
			
			// aapt resource value: 0x7f080013
			public const int txt_FAPesoBruto = 2131230739;
			
			// aapt resource value: 0x7f08002a
			public const int txt_FAPesoBrutoRecogido = 2131230762;
			
			// aapt resource value: 0x7f080015
			public const int txt_FAPesoNeto = 2131230741;
			
			// aapt resource value: 0x7f08002c
			public const int txt_FAPesoNetoRecogido = 2131230764;
			
			// aapt resource value: 0x7f080014
			public const int txt_FAPesoTara = 2131230740;
			
			// aapt resource value: 0x7f08002b
			public const int txt_FAPesoTaraRecogido = 2131230763;
			
			// aapt resource value: 0x7f080016
			public const int txt_FAPesoTotal = 2131230742;
			
			// aapt resource value: 0x7f080009
			public const int txt_FAPobliacion = 2131230729;
			
			// aapt resource value: 0x7f080020
			public const int txt_FAPobliacionRecogido = 2131230752;
			
			// aapt resource value: 0x7f08000b
			public const int txt_FATfn1 = 2131230731;
			
			// aapt resource value: 0x7f080022
			public const int txt_FATfn1Recogido = 2131230754;
			
			// aapt resource value: 0x7f08000c
			public const int txt_FATfn2 = 2131230732;
			
			// aapt resource value: 0x7f080023
			public const int txt_FATfn2Recogido = 2131230755;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int ConexionBascula = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int FichaAviso = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int FichaAvisoRecogido = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Lista = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ListaAviso = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ListaAvisosRecogidos = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ListaMotivos = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int Login = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Main = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int Menu = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int menu_opciones = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int menu_salir = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int menus_recogidos = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int MotivosAnulacion = 2130968589;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int hojatrabajo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ic_render = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Icon = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int imprimirhojatrabajo = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int pendientes = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int recogidos = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int sincronizacion = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int sincronizar = 2130903047;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int app_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int ActionBarTheme = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int ActionBarTitleText = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int Render = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int RenderRojo = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int RenderVerde = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int RenderVioleta = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
